# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Pastikan token ini sudah ditambahkan ke Secrets
      run: |
        npm install -g sonar-scanner
        sonar-scanner -Dsonar.projectKey=your_project_key \
                       -Dsonar.organization=your_organization \
                       -Dsonar.host.url=https://sonarcloud.io \
                       -Dsonar.sources=. \
                       -Dsonar.language=js \
                       -Dsonar.sourceEncoding=UTF-8
